### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by Bence98007** [h4rdee/Hard-Hook-Reborn-CSNZ#1]
Hi Hardee!
Im planning to make this work, is it already working or do you have any info about this opengl hax?
I saw that lot of trash code included, but I can fix that and make a pull request if you want.

Thanks! :)

**Comment by h4rdee** [comment]
@Bence98007 it **was** working back in a day, however, anticheat bypass isnt included in this repo, so you gotta have to figure it out yourself. i will glad to see any pull requests though
